version: '3.8'

services:
  # 1. Base de Datos
  db:
    image: postgres:15-alpine
    container_name: task-manager-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taskdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend
  backend:
    build: ./backend
    container_name: task-manager-backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      # Conectamos con el servicio 'db' definido arriba
      DATABASE_URL: 'postgresql://user:password123@db:5432/taskdb?schema=public'
      JWT_SECRET: 'mi_secreto_super_seguro'
      FRONTEND_URL: 'http://localhost:4173' # URL donde correrá el frontend

  # 3. Frontend
  frontend:
    build: ./frontend
    container_name: task-manager-frontend
    ports:
      - '4173:4173'
    environment:
      # El navegador necesita saber dónde está la API (localhost porque el browser corre en tu PC, no en Docker)
      VITE_API_URL: 'http://localhost:3000'
    depends_on:
      - backend

volumes:
  postgres_data:
